# Particle Compile Action Workflow
name: Particle Compile

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Particle Compile Action
      - name: Compile Firmware
        id: compile
        uses: particle-iot/compile-action@v1
        with:
          # 1. 设置平台：Photon 2 的代号就是 'p2'
          particle-platform-name: 'p2'
          # 2. 指定 Device OS 版本：这里填入你需要的版本
          device-os-version: '6.3.3'

      # Upload compiled firmware as an artifact on GitHub.
      - name: Upload Firmware as Artifact
        # 3. 修复报错：这里从 v3 改成了 v4
        uses: actions/upload-artifact@v4
        with:
          name: firmware-artifact
          path: |
            ${{ steps.compile.outputs.firmware-path }}
            ${{ steps.compile.outputs.target-path }}
